allow_entities_without_labels: true
index: false
testmode: false
batch: true
safe_label: loose
batch_size: 100000000
relation_type_threshold: 0.95
represent_values_and_annotations_as_json:
  iris:
    - "http://purl.obolibrary.org/obo/IAO_0000115"
    - "http://www.geneontology.org/formats/oboInOwl#hasExactSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym"

neo_node_labelling:
  - classes:
      - CL:0011005
      - BDSHELP:exemplar_of some CL:0011005
    label: GABAergic
  - classes:
      - CL:0000679
      - BDSHELP:exemplar_of some CL:0000679
    label: Glutamatergic
  - classes:
      - CL:0002453
      - BDSHELP:exemplar_of some CL:0002453
    label: OPC
  - classes:
      - CL:0000127
      - BDSHELP:exemplar_of some CL:0000127
    label: Astrocyte
  - classes:
      - CL:0000128
      - BDSHELP:exemplar_of some CL:0000128
    label: Oligodendrocyte
  - classes:
      - CL:0000115
      - BDSHELP:exemplar_of some CL:0000115
    label: Endothelial
  - classes:
      - CL:0000359
      - BDSHELP:exemplar_of some CL:0000359
    label: SMC
  - classes:
      - CL:0000669
      - BDSHELP:exemplar_of some CL:0000669
    label: Pericyte
  - classes:
      - CL:0000129
      - BDSHELP:exemplar_of some CL:0000129
    label: Microglial
  - classes:
      - CL:4023051
      - BDSHELP:exemplar_of some CL:0000129
    label: VLMC
  - classes:
      - CL:4023065
      - BDSHELP:exemplar_of some CL:4023065
    label: Meis2
  - classes:
      - UBERON:0002616
      - BDSHELP:exemplar_of some UBERON:0002616
    label: Brain_Region
  - classes:
      - SO:0000704
      - BDSHELP:exemplar_of some SO:0000704
    label: Gene
  - classes:
      - BDSHELP:Cluster
      - BDSHELP:exemplar_of some BDSHELP:Cluster
    label: Cluster
  - classes:
      - OBI:0100026
      - BDSHELP:exemplar_of some OBI:0100026
    label: Organism
  - classes:
      - PATO:0010006
      - BDSHELP:exemplar_of some PATO:0010006
    label: morphology
  - classes:
      - PATO:0070033
      - BDSHELP:exemplar_of some PATO:0070033
    label: projection
##Morphological subclasses##
  - classes:
      - CL:0000104
      - BDSHELP:exemplar_of some CL:0000104
    label: Multipolar
  - classes:
      - CL:0000598
      - BDSHELP:exemplar_of some CL:0000598
    label: Pyramidal
  - classes:
      - CL:4023066
      - BDSHELP:exemplar_of some CL:4023066
    label: Horizontal_pyramidal
  - classes:
      - CL:4023092
      - BDSHELP:exemplar_of some CL:4023092
    label: Inverted_pyramidal
  - classes:
      - CL:4023093
      - BDSHELP:exemplar_of some CL:4023093
    label: Stellate_pyramidal
  - classes:
      - CL:4023094
      - BDSHELP:exemplar_of some CL:4023094
    label: Tufted_pyramidal
  - classes:
      - CL:4023095
      - BDSHELP:exemplar_of some CL:4023095
    label: Untufted_pyramidal
  - classes:
      - CL:4023076
      - BDSHELP:exemplar_of some CL:4023076
    label: Martinotti
  - classes:
      - CL:4023087
      - BDSHELP:exemplar_of some CL:4023087
    label: Fan_Martinotti
  - classes:
      - CL:4023086
      - BDSHELP:exemplar_of some CL:4023086
    label: T_Martinotti
  - classes:
      - CL:0000118
      - BDSHELP:exemplar_of some CL:0000118
    label: Basket
  - classes:
      - CL:4023088
      - BDSHELP:exemplar_of some CL:4023088
    label: Large_basket
  - classes:
      - CL:4023090
      - BDSHELP:exemplar_of some CL:4023090
    label: Small_basket
  - classes:
      - CL:4023089
      - BDSHELP:exemplar_of some CL:4023089
    label: Nest_basket
  - classes:
      - CL:0000693
      - BDSHELP:exemplar_of some CL:0000693
    label: Neurogliaform
  - classes:
      - CL:4023083
      - BDSHELP:exemplar_of some CL:4023083
    label: Chandelier
  - classes:
      - CL:4023077
      - BDSHELP:exemplar_of some CL:4023077
    label: Bitufted
  - classes:
      - CL:0000103
      - BDSHELP:exemplar_of some CL:0000103
    label: Bipolar
##Projection subclasses##
  - classes:
      - RO:0000053 some PATO:0070028
    label: Extratelencephalic
  - classes:
      - RO:0000053 some PATO:0070034
    label: Intratelencephalic
  - classes:
      - RO:0000053 some PATO:0070029
    label: Corticothalamic
  - classes:
      - RO:0000053 some PATO:0070030
    label: Near_projecting
  - classes:
      - RO:0000053 some PATO:0070031
    label: Corticomedulla

curie_map:
  GITHUB: https://github.com/
  GITHUBH: http://github.com/
  PMID: http://www.ncbi.nlm.nih.gov/pubmed/
  orcid: https://orcid.org/
  doi: https://doi.org/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ncbigene: http://www.ncbi.nlm.nih.gov/gene/
  cc: http://creativecommons.org/ns#
  pato_rel: http://purl.obolibrary.org/obo/pato#
  so_rel: http://purl.obolibrary.org/obo/so#
  ro_rel: http://www.obofoundry.org/ro/ro.owl#
  owl: http://www.w3.org/2002/07/owl#
  BDSHELP: http://www.semanticweb.org/brain_data_standards/helper.owl#
  AllenDend: http://www.semanticweb.org/brain_data_standards/AllenDend_
  skos: http://www.w3.org/2004/02/skos/core#
  ensembl: http://identifiers.org/ensembl/
  RO: http://purl.obolibrary.org/obo/RO_
  UBERON: http://purl.obolibrary.org/obo/UBERON_
  CL: http://purl.obolibrary.org/obo/CL_
  AllenDendClass: http://www.semanticweb.org/brain_data_standards/AllenDendClass_
  n2o: http://n2o.neo/custom/
  ILX: http://uri.interlex.org/base/ilx_
  NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
  PR: http://purl.obolibrary.org/obo/PR_
  SO: http://purl.obolibrary.org/obo/SO_
  OBI: http://purl.obolibrary.org/obo/OBI_

filters:
  solr:
    exclusion:
      iri_prefix:
        - http://virtualflybrain.org/reports/VFBc_
      neo4j_node_label:
        - Channel
